[package]
name = "druid_counter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# druid = "0.7.0"            # did not work
druid = { git = "https://github.com/linebender/druid.git" }
